MAPPING = [
    {
        'sid': 'Adult age binary (yes)',
        'symptom': 'age',
        'module': 'adult',
        'gen_5_4a': 55,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (no)',
        'symptom': 'age',
        'module': 'adult',
        'gen_5_4a': 45,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (no-lower bound)',
        'symptom': 'age',
        'module': 'adult',
        'gen_5_4a': 12,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (threshold)',
        'symptom': 'age',
        'module': 'adult',
        'gen_5_4a': 49,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (just age group)',
        'symptom': 'age',
        'module': 'adult',
        'gen_5_4d': 3,
        'endorsed': False,
    },
    {
        'sid': 'Adult-first age quartile (yes)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4a': 20,
        'endorsed': True,
    },
    {
        'sid': 'Adult-first age quartile (yes-upper threshold)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4a': 32,
        'endorsed': True,
    },
    {
        'sid': 'Adult-first age quartile (yes-lower threshold)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4a': 12,
        'endorsed': True,
    },
    {
        'sid': 'Adult-first age quartile (no)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4a': 35,
        'endorsed': False,
    },
    {
        'sid': 'Adult-first age quartile (no-upper threshold)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4a': 33,
        'endorsed': False,
    },
    {
        'sid': 'Adult-first age quartile (just age group)',
        'symptom': 's88881',
        'module': 'adult',
        'gen_5_4d': 3,
        'endorsed': False,
    },
    {
        'sid': 'Adult-second age quartile (yes)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 40,
        'endorsed': True,
    },
    {
        'sid': 'Adult-second age quartile (yes-upper threshold)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 49,
        'endorsed': True,
    },
    {
        'sid': 'Adult-second age quartile (yes-lower threshold)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 33,
        'endorsed': True,
    },
    {
        'sid': 'Adult-second age quartile (no-upper)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 60,
        'endorsed': False,
    },
    {
        'sid': 'Adult-second age quartile (no-lower)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 30,
        'endorsed': False,
    },
    {
        'sid': 'Adult-second age quartile (no-lower threshold)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 32,
        'endorsed': False,
    },
    {
        'sid': 'Adult-second age quartile (no-upper threshold)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4a': 50,
        'endorsed': False,
    },
    {
        'sid': 'Adult-second age quartile (just age group)',
        'symptom': 's88882',
        'module': 'adult',
        'gen_5_4d': 3,
        'endorsed': False,
    },
    {
        'sid': 'Adult-third age quartile (yes)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 50,
        'endorsed': True,
    },
    {
        'sid': 'Adult-third age quartile (yes-upper threshold)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 65,
        'endorsed': True,
    },
    {
        'sid': 'Adult-third age quartile (yes-lower threshold)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 50,
        'endorsed': True,
    },
    {
        'sid': 'Adult-third age quartile (no-lower)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 40,
        'endorsed': False,
    },
    {
        'sid': 'Adult-third age quartile (no-upper)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 70,
        'endorsed': False,
    },
    {
        'sid': 'Adult-third age quartile (no-lower threshold)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 49,
        'endorsed': False,
    },
    {
        'sid': 'Adult-third age quartile (no-upper threshold)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4a': 66,
        'endorsed': False,
    },
    {
        'sid': 'Adult-third age quartile (just age group)',
        'symptom': 's88883',
        'module': 'adult',
        'gen_5_4d': 3,
        'endorsed': False,
    },
    {
        'sid': 'Adult-fourth age quartile (yes)',
        'symptom': 's88884',
        'module': 'adult',
        'gen_5_4a': 70,
        'endorsed': True,
    },
    {
        'sid': 'Adult-fourth age quartile (yes-lower threshold)',
        'symptom': 's88884',
        'module': 'adult',
        'gen_5_4a': 66,
        'endorsed': True,
    },
    {
        'sid': 'Adult-fourth age quartile (no-lower)',
        'symptom': 's88884',
        'module': 'adult',
        'gen_5_4a': 60,
        'endorsed': False,
    },
    {
        'sid': 'Adult-fourth age quartile (no-lower threshold)',
        'symptom': 's88884',
        'module': 'adult',
        'gen_5_4a': 65,
        'endorsed': False,
    },
    {
        'sid': 'Adult-fourth age quartile (just age group)',
        'symptom': 's88884',
        'module': 'adult',
        'gen_5_4d': 3,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (years-yes)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4a': 7,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (years-upper bound)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4a': 11,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (years-no)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4a': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (years-threshold)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4a': 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (months-yes)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4b': 30,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (months-no)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4b': 11,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (months-threshold)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4b': 24,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (days-yes)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4c': 365 * 3,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (days-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4c': 29,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (days-threshold)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4c': 365 * 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (just age group)',
        'symptom': 'age',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (no-years)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4a': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (yes-months)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4b': 3,
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (yes-months lower threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4b': 1,
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (yes-months upper threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4b': 5,
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (no-months)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4b': 11,
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (no-months upper threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4b': 6,
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (yes-days)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4c': 100,
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (yes-days lower threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4c': 29,
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (yes-days upper threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4c': 152,   # FIXME: rounding error converting days
        'endorsed': True,
    },
    {
        'sid': 'Child-first age quintile (no-days)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4c': 300,
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (no-days upper threshold)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4c': 153,   # FIXME: rounding error converting days
        'endorsed': False,
    },
    {
        'sid': 'Child-first age quintile (just age group)',
        'symptom': 's2991',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (yes-years upper threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4a': 1,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (no-years)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4a': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (yes-months)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 9,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (yes-months upper threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 12,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (yes-months lower threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 6,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (no-months upper)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 15,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-months lower)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 3,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-months upper threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 13,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-months lower threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4b': 5,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (yes-days)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 300,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (yes-days upper threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 365,
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (yes-days lower threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 153,   # FIXME: rounding error converting days
        'endorsed': True,
    },
    {
        'sid': 'Child-second age quintile (no-days upper)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 500,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-days lower)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 60,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-days upper threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 366,
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (no-days lower threshold)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4c': 152,   # FIXME: rounding error converting days
        'endorsed': False,
    },
    {
        'sid': 'Child-second age quintile (just age group)',
        'symptom': 's2992',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (yes-years lower threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4a': 2,
        'endorsed': True,
    },
    {
        'sid': 'Child-third age quintile (yes-years upper threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4a': 3,
        'endorsed': True,
    },
    {
        'sid': 'Child-third age quintile (no-years upper)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4a': 5,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (no-years lower threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4a': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (no-years upper threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4a': 4,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (yes-months)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 30,
        'endorsed': True,
    },
    {
        'sid': 'Child-third age quintile (yes-months upper threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 36,
        'endorsed': True,
    },
    {
        'sid': 'Child-third age quintile (yes-months lower threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 13,
        'endorsed': True,
    },
    {
        'sid': 'Child-third age quintile (no-months lower)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 10,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (no-months upper)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 60,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (no-months lower threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 12,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (no-months upper threshold)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4b': 37,
        'endorsed': False,
    },
    {
        'sid': 'Child-third age quintile (just age group)',
        'symptom': 's2993',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (yes-years)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 5,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (yes-years upper threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 7,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (yes-years lower threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 4,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (no-years lower)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-years upper)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 10,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-years lower threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 3,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-years upper threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4a': 8,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (yes-months)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 60,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (yes-months upper threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 84,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (yes-months lower threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 48,
        'endorsed': True,
    },
    {
        'sid': 'Child-fourth age quintile (no-months lower)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 30,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-months upper)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 120,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-months lower threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 36,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (no-months upper threshold)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4b': 96,
        'endorsed': False,
    },
    {
        'sid': 'Child-fourth age quintile (just age group)',
        'symptom': 's2994',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Child-fifth age quintile (yes)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4a': 9,
        'endorsed': True,
    },
    {
        'sid': 'Child-fifth age quintile (yes-upper)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4a': 11,
        'endorsed': True,
    },
    {
        'sid': 'Child-fifth age quintile (yes-lower)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4a': 8,
        'endorsed': True,
    },
    {
        'sid': 'Child-fifth age quintile (no-years)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4a': 5,
        'endorsed': False,
    },
    {
        'sid': 'Child-fifth age quintile (no-lower threshold)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4a': 7,
        'endorsed': False,
    },
    {
        'sid': 'Child-fifth age quintile (just age group)',
        'symptom': 's2995',
        'module': 'child',
        'gen_5_4d': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (yes)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4c': 5,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (yes-upper bound)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4c': 28,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (no)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4c': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (zero)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4c': 0,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (threshold)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4c': 3,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (just age group)',
        'symptom': 'age',
        'module': 'neonate',
        'gen_5_4d': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-first age quartile (yes)',
        'symptom': 's4991',
        'module': 'neonate',
        'gen_5_4c': 0,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-first age quartile (no)',
        'symptom': 's4991',
        'module': 'neonate',
        'gen_5_4c': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-first age quartile (just age group)',
        'symptom': 's4991',
        'module': 'neonate',
        'gen_5_4d': 1,
        'endorsed': True,  # FIXME: neonate age defaults to zero
    },
    # There is a s4992
    {
        'sid': 'Neonate-third age quartile (yes-lower)',
        'symptom': 's4993',
        'module': 'neonate',
        'gen_5_4c': 1,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-third age quartile (yes-upper)',
        'symptom': 's4993',
        'module': 'neonate',
        'gen_5_4c': 2,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-third age quartile (no-lower)',
        'symptom': 's4993',
        'module': 'neonate',
        'gen_5_4c': 0,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-third age quartile (no-upper)',
        'symptom': 's4993',
        'module': 'neonate',
        'gen_5_4c': 3,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-third age quartile (just age group)',
        'symptom': 's4993',
        'module': 'neonate',
        'gen_5_4d': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-fourth age quartile (yes)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4c': 12,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-fourth age quartile (yes-lower)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4c': 3,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-fourth age quartile (yes-upper)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4c': 28,
        'endorsed': True,
    },
    {
        'sid': 'Neonate-fourth age quartile (no)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4c': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-fourth age quartile (no-lower)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4c': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate-fourth age quartile (just age group)',
        'symptom': 's4994',
        'module': 'neonate',
        'gen_5_4d': 1,
        'endorsed': False,
    },
]
