"""Test lookup for values dependent on other values.

Duration columns have a unit column and a value column. If the unit column has
a valid value and the value column is missing, it is possible the code will
throw a KeyError. The other suites can test if a missing value (empty string)
or an illegal value (such as 'XXX') are present. This suite explicitly does not
include the secondary dependent columns to test for KeyErrors

"""
MAPPING = [
    {
        'sid': 'Adult illness duration (years)',
        'module': 'adult',
        'symptom': 's15',
        'endorsed': False,
        'adult_2_1': 1,
    },
    {
        'sid': 'Adult illness duration (months)',
        'module': 'adult',
        'symptom': 's15',
        'endorsed': False,
        'adult_2_1': 2,
    },
    {
        'sid': 'Adult illness duration (days)',
        'module': 'adult',
        'symptom': 's15',
        'endorsed': False,
        'adult_2_1': 4,
    },
    {
        'sid': 'Adult illness duration (hours)',
        'module': 'adult',
        'symptom': 's15',
        'endorsed': False,
        'adult_2_1': 5,
    },
    {
        'sid': 'Adult fever duration',
        'module': 'adult',
        'symptom': 's17',
        'endorsed': False,
        'adult_2_3': 4,
    },
    {
        'sid': 'Adult rash duration',
        'module': 'adult',
        'symptom': 's22',
        'endorsed': False,
        'adult_2_8': 4,
    },
    {
        'sid': 'Adult foot ulcer duration',
        'module': 'adult',
        'symptom': 's32',
        'endorsed': False,
        'adult_2_15': 4,
    },
    {
        'sid': 'Adult yellow eyes duration (days)',
        'module': 'adult',
        'symptom': 's39',
        'endorsed': False,
        'adult_2_22': 4,
    },
    {
        'sid': 'Adult yellow eyes duration (months)',
        'module': 'adult',
        'symptom': 's39',
        'endorsed': False,
        'adult_2_22': 2,
    },
    {
        'sid': 'Adult ankle swelling duration (days)',
        'module': 'adult',
        'symptom': 's41',
        'endorsed': False,
        'adult_2_24': 4,
    },
    {
        'sid': 'Adult ankle swelling duration (months)',
        'module': 'adult',
        'symptom': 's41',
        'endorsed': False,
        'adult_2_24': 2,
    },
    {
        'sid': 'Adult puffy face duration (days)',
        'module': 'adult',
        'symptom': 's43',
        'endorsed': False,
        'adult_2_26': 4,
    },
    {
        'sid': 'Adult puffy face duration (months)',
        'module': 'adult',
        'symptom': 's43',
        'endorsed': False,
        'adult_2_26': 2,
    },
    {
        'sid': 'Adult puffy body duration (days)',
        'module': 'adult',
        'symptom': 's45',
        'endorsed': False,
        'adult_2_28': 4,
    },
    {
        'sid': 'Adult puffy body duration (months)',
        'module': 'adult',
        'symptom': 's45',
        'endorsed': False,
        'adult_2_28': 2,
    },
    {
        'sid': 'Adult cough duration (days)',
        'module': 'adult',
        'symptom': 's50',
        'endorsed': False,
        'adult_2_33': 4,
    },
    {
        'sid': 'Adult cough duration (months)',
        'module': 'adult',
        'symptom': 's50',
        'endorsed': False,
        'adult_2_33': 2,
    },
    {
        'sid': 'Adult difficult breathing duration (days)',
        'module': 'adult',
        'symptom': 's54',
        'endorsed': False,
        'adult_2_37': 4,
    },
    {
        'sid': 'Adult difficult breathing duration (months)',
        'module': 'adult',
        'symptom': 's54',
        'endorsed': False,
        'adult_2_37': 2,
    },
    {
        'sid': 'Adult fast breathing duration (days)',
        'module': 'adult',
        'symptom': 's59',
        'endorsed': False,
        'adult_2_41': 4,
    },
    {
        'sid': 'Adult fast breathing duration (months)',
        'module': 'adult',
        'symptom': 's59',
        'endorsed': False,
        'adult_2_41': 2,
    },
    {
        'sid': 'Adult diarrhea duration',
        'module': 'adult',
        'symptom': 's67',
        'endorsed': False,
        'adult_2_48': 4,
    },
    {
        'sid': 'Adult vomit duration (days)',
        'module': 'adult',
        'symptom': 's73',
        'endorsed': False,
        'adult_2_54': 4,
    },
    {
        'sid': 'Adult vomit duration (hours)',
        'module': 'adult',
        'symptom': 's73',
        'endorsed': False,
        'adult_2_54': 5,
    },
    {
        'sid': 'Adult difficulty swallowing duration (days)',
        'module': 'adult',
        'symptom': 's77',
        'endorsed': False,
        'adult_2_58': 4,
    },
    {
        'sid': 'Adult difficulty swallowing duration (months)',
        'module': 'adult',
        'symptom': 's77',
        'endorsed': False,
        'adult_2_58': 2,
    },
    {
        'sid': 'Adult belly pain duration (hours)',
        'module': 'adult',
        'symptom': 's81',
        'endorsed': False,
        'adult_2_62': 5,
    },
    {
        'sid': 'Adult belly pain duration (days)',
        'module': 'adult',
        'symptom': 's81',
        'endorsed': False,
        'adult_2_62': 4,
    },
    {
        'sid': 'Adult belly pain duration (months)',
        'module': 'adult',
        'symptom': 's81',
        'endorsed': False,
        'adult_2_62': 2,
    },
    {
        'sid': 'Adult protruding belly duration (days)',
        'module': 'adult',
        'symptom': 's85',
        'endorsed': False,
        'adult_2_65': 4,
    },
    {
        'sid': 'Adult protruding belly duration (months)',
        'module': 'adult',
        'symptom': 's85',
        'endorsed': False,
        'adult_2_65': 2,
    },
    {
        'sid': 'Adult mass in belly duration (days)',
        'module': 'adult',
        'symptom': 's88',
        'endorsed': False,
        'adult_2_68': 4,
    },
    {
        'sid': 'Adult mass in belly duration (months)',
        'module': 'adult',
        'symptom': 's88',
        'endorsed': False,
        'adult_2_68': 2,
    },
    {
        'sid': 'Adult headache duration (hours)',
        'module': 'adult',
        'symptom': 's90',
        'endorsed': False,
        'adult_2_70': 5,
    },
    {
        'sid': 'Adult headache duration (days)',
        'module': 'adult',
        'symptom': 's90',
        'endorsed': False,
        'adult_2_70': 4,
    },
    {
        'sid': 'Adult stiff neck duration (days)',
        'module': 'adult',
        'symptom': 's93',
        'endorsed': False,
        'adult_2_73': 4,
    },
    {
        'sid': 'Adult stiff neck duration (months)',
        'module': 'adult',
        'symptom': 's93',
        'endorsed': False,
        'adult_2_73': 2,
    },
    {
        'sid': 'Adult unconsciousness duration (days)',
        'module': 'adult',
        'symptom': 's96',
        'endorsed': False,
        'adult_2_76': 4,
    },
    {
        'sid': 'Adult unconsciousness duration (months)',
        'module': 'adult',
        'symptom': 's96',
        'endorsed': False,
        'adult_2_76': 2,
    },
    {
        'sid': 'Adult confusion duration (days)',
        'module': 'adult',
        'symptom': 's99',
        'endorsed': False,
        'adult_2_79': 4,
    },
    {
        'sid': 'Adult confusion duration (months)',
        'module': 'adult',
        'symptom': 's99',
        'endorsed': False,
        'adult_2_79': 2,
    },
    {
        'sid': 'Adult convulsions duration (hours)',
        'module': 'adult',
        'symptom': 's103',
        'endorsed': False,
        'adult_2_83': 5,
    },
    {
        'sid': 'Adult convulsions duration (minutes)',
        'module': 'adult',
        'symptom': 's103',
        'endorsed': False,
        'adult_2_83': 6,
    },
    {
        'sid': 'Adult paralysis duration (days)',
        'module': 'adult',
        'symptom': 's106',
        'endorsed': False,
        'adult_2_86': 4,
    },
    {
        'sid': 'Adult paralysis duration (months)',
        'module': 'adult',
        'symptom': 's106',
        'endorsed': False,
        'adult_2_86': 2,
    },
    {
        'sid': 'Adult paralysis duration (years)',
        'module': 'adult',
        'symptom': 's106',
        'endorsed': False,
        'adult_2_86': 1,
    },
    {
        'sid': 'Adult period overdue duration (weeks)',
        'module': 'adult',
        'symptom': 's125',
        'endorsed': False,
        'adult_3_8': 3,
    },
    {
        'sid': 'Adult pregnant duration (months)',
        'module': 'adult',
        'symptom': 's128',
        'endorsed': False,
        'adult_3_11': 2,
    },
    {
        'sid': 'Adult labor duration (hours)',
        'module': 'adult',
        'symptom': 's133',
        'endorsed': False,
        'adult_3_16': 5,
    },
    {
        'sid': 'Adult injury duration (years)',
        'module': 'adult',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'adult_5_2': '1 2 3 4 5 6 7',
        'adult_5_5': 1
    },
    {
        'sid': 'Adult injury duration (months)',
        'module': 'adult',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'adult_5_2': '1 2 3 4 5 6 7',
        'adult_5_5': 2
    },
    {
        'sid': 'Adult injury duration (days)',
        'module': 'adult',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'adult_5_2': '1 2 3 4 5 6 7',
        'adult_5_5': 4
    },
    {
        'sid': 'Adult injury duration (hours)',
        'module': 'adult',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'adult_5_2': '1 2 3 4 5 6 7',
        'adult_5_5': 5
    },
    {
        'sid': 'Child mother died after delivery duration (days)',
        'module': 'child',
        'symptom': 's9',
        'endorsed': False,
        'child_1_5': 4,
    },
    {
        'sid': 'Child mother died after delivery duration (months)',
        'module': 'child',
        'symptom': 's9',
        'endorsed': False,
        'child_1_5': 2,
    },
    {
        'sid': 'Child birth weight (grams)',
        'module': 'child',
        'symptom': 's14',
        'endorsed': False,
        'child_1_8': 1,
    },
    {
        'sid': 'Child birth weight (kilograms)',
        'module': 'child',
        'symptom': 's14',
        'endorsed': False,
        'child_1_8': 2,
    },
    {
        'sid': 'Child age illness started (days)',
        'module': 'child',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 4,
    },
    {
        'sid': 'Child age illness started (months)',
        'module': 'child',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 2,
    },
    {
        'sid': 'Child age illness started (years)',
        'module': 'child',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 1,
    },
    {
        'sid': 'Child illness duration (days)',
        'module': 'child',
        'symptom': 's29',
        'endorsed': False,
        'child_1_21': 4,
    },
    {
        'sid': 'Child illness duration (months)',
        'module': 'child',
        'symptom': 's29',
        'endorsed': False,
        'child_1_21': 2,
    },
    {
        'sid': 'Child fever duration',
        'module': 'child',
        'symptom': 's111',
        'endorsed': False,
        'child_4_2': 2,
    },
    {
        'sid': 'Child diarrhea duration',
        'module': 'child',
        'symptom': 's117',
        'endorsed': False,
        'child_4_8': 2,
    },
    {
        'sid': 'Child stools stop before death duration',
        'module': 'child',
        'symptom': 's119',
        'endorsed': False,
        'child_4_10': 2,
    },
    {
        'sid': 'Child cough duration (days)',
        'module': 'child',
        'symptom': 's122',
        'endorsed': False,
        'child_4_13': 4,
    },
    {
        'sid': 'Child difficult breathing duration (days)',
        'module': 'child',
        'symptom': 's126',
        'endorsed': False,
        'child_4_17': 4,
    },
    {
        'sid': 'Child fast breathing duration (days)',
        'module': 'child',
        'symptom': 's128',
        'endorsed': False,
        'child_4_19': 4,
    },
    {
        'sid': 'Child rash duration (days)',
        'module': 'child',
        'symptom': 's142',
        'endorsed': False,
        'child_4_33': 4,
    },
    {
        'sid': 'Child swelling duration (days)',
        'module': 'child',
        'symptom': 's146',
        'endorsed': False,
        'child_4_37': 4,
    },
    {
        'sid': 'Child swelling duration (weeks)',
        'module': 'child',
        'symptom': 's146',
        'endorsed': False,
        'child_4_37': 3,
    },
    {
        'sid': 'Child injury duration (days)',
        'module': 'child',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'child_4_48': '1 2 3 4 5 6 7',
        'child_4_50': 4
    },
    {
        'sid': 'Child injury duration (hours)',
        'module': 'child',
        'symptom': 's155',
        'endorsed': True,  # no injury duration leads to endorsement
        'child_4_48': '1 2 3 4 5 6 7',
        'child_4_50': 5
    },
    {
        'sid': 'Neonate mother died after delivery duration (days)',
        'module': 'neonate',
        'symptom': 's9',
        'endorsed': False,
        'child_1_5': 4,
    },
    {
        'sid': 'Neonate mother died after delivery duration (months)',
        'module': 'neonate',
        'symptom': 's9',
        'endorsed': False,
        'child_1_5': 2,
    },
    {
        'sid': 'Neonate birth weight (grams)',
        'module': 'neonate',
        'symptom': 's14',
        'endorsed': False,
        'child_1_8': 1,
    },
    {
        'sid': 'Neonate birth weight (kilograms)',
        'module': 'neonate',
        'symptom': 's14',
        'endorsed': False,
        'child_1_8': 2,
    },
    {
        'sid': 'Neonate age illness started (days)',
        'module': 'neonate',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 4,
    },
    {
        'sid': 'Neonate age illness started (months)',
        'module': 'neonate',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 2,
    },
    {
        'sid': 'Neonate age illness started (years)',
        'module': 'neonate',
        'symptom': 's28',
        'endorsed': False,
        'child_1_20': 1,
    },
    {
        'sid': 'Neonate illness duration (days)',
        'module': 'neonate',
        'symptom': 's29',
        'endorsed': False,
        'child_1_21': 4,
    },
    {
        'sid': 'Neonate illness duration (months)',
        'module': 'neonate',
        'symptom': 's29',
        'endorsed': False,
        'child_1_21': 2,
    },
    {
        'sid': 'Neonate pregnancy duration (months)',
        'module': 'neonate',
        'symptom': 's45',
        'endorsed': False,
        'child_2_2': 2,
    },
    {
        'sid': 'Neonate last feel baby move (days)',
        'module': 'neonate',
        'symptom': 's48',
        'endorsed': False,
        'child_2_5': 4,
    },
    {
        'sid': 'Neonate last feel baby move (hours)',
        'module': 'neonate',
        'symptom': 's48',
        'endorsed': False,
        'child_2_5': 5,
    },
    {
        'sid': 'Neonate delivery duration (hours)',
        'module': 'neonate',
        'symptom': 's53',
        'endorsed': False,
        'child_2_10': 5,
    },
    {
        'sid': 'Neonate stopped being able to suckle (days)',
        'module': 'neonate',
        'symptom': 's75',
        'endorsed': False,
        'child_3_14': 4,
    },
    {
        'sid': 'Neonate age difficult breathing started (days)',
        'module': 'neonate',
        'symptom': 's79',
        'endorsed': False,
        'child_3_18': 4,
    },
    {
        'sid': 'Neonate difficult breathing duration (days)',
        'module': 'neonate',
        'symptom': 's80',
        'endorsed': False,
        'child_3_19': 4,
    },
    {
        'sid': 'Neonate age fast breathing started (days)',
        'module': 'neonate',
        'symptom': 's82',
        'endorsed': False,
        'child_3_21': 4,
    },
    {
        'sid': 'Neonate fast breathing duration (days)',
        'module': 'neonate',
        'symptom': 's83',
        'endorsed': False,
        'child_3_22': 4,
    },
    {
        'sid': 'Neonate age fever started (days)',
        'module': 'neonate',
        'symptom': 's88',
        'endorsed': False,
        'child_3_27': 4,
    },
    {
        'sid': 'Neonate fever duration (days)',
        'module': 'neonate',
        'symptom': 's89',
        'endorsed': False,
        'child_3_28': 4,
    },
    {
        'sid': 'Neonate age became cold to touch (days)',
        'module': 'neonate',
        'symptom': 's91',
        'endorsed': False,
        'child_3_30': 4,
    },
    {
        'sid': 'Neonate cold to touch duration (days)',
        'module': 'neonate',
        'symptom': 's92',
        'endorsed': False,
        'child_3_31': 4,
    },
]
