MAPPING = [
    {
        'sid': 'Adult age binary (ageInYears-yes)',
        'symptom': 'age',
        'module': 'adult',
        'ageInYears': 55,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (ageInYears-no)',
        'symptom': 'age',
        'module': 'adult',
        'ageInYears': 45,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (ageInYears-threshold)',
        'symptom': 'age',
        'module': 'adult',
        'ageInYears': 49,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (ageInYears-lower bound)',
        'symptom': 'age',
        'module': 'adult',
        'ageInYears': 12,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (age_adult-yes)',
        'symptom': 'age',
        'module': 'adult',
        'age_adult': 55,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (age_adult-no)',
        'symptom': 'age',
        'module': 'adult',
        'age_adult': 45,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (age_adult-threshold)',
        'symptom': 'age',
        'module': 'adult',
        'age_adult': 49,
        'endorsed': True,
    },
    {
        'sid': 'Adult age binary (age_adult-lower bound)',
        'symptom': 'age',
        'module': 'adult',
        'age_adult': 12,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (isAdult)',
        'symptom': 'age',
        'module': 'adult',
        'isAdult': 1,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (isAdult1)',
        'symptom': 'age',
        'module': 'adult',
        'isAdult1': 1,
        'endorsed': False,
    },
    {
        'sid': 'Adult age binary (isAdult2)',
        'symptom': 'age',
        'module': 'adult',
        'isAdult2': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInYears-yes)',
        'symptom': 'age',
        'module': 'child',
        'ageInYears': 7,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInYears-yes)',
        'symptom': 'age',
        'module': 'child',
        'ageInYears': 7,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInYears-upper bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInYears': 11,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInYears-threshold)',
        'symptom': 'age',
        'module': 'child',
        'ageInYears': 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInYears-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInYears': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (age_child_years-yes)',
        'symptom': 'age',
        'module': 'child',
        'age_child_years': 7,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (age_child_years-upper bound)',
        'symptom': 'age',
        'module': 'child',
        'age_child_years': 11,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (age_child_years-threshold)',
        'symptom': 'age',
        'module': 'child',
        'age_child_years': 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (age_child_years-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'age_child_years': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInMonths-yes)',
        'symptom': 'age',
        'module': 'child',
        'ageInMonths': 40,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInMonths-no)',
        'symptom': 'age',
        'module': 'child',
        'ageInMonths': 15,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInMonths-threshold)',
        'symptom': 'age',
        'module': 'child',
        'ageInMonths': 24,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInMonths-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInMonths': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (age_child_months-yes)',
        'symptom': 'age',
        'module': 'child',
        'age_child_months': 40,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (age_child_months-no)',
        'symptom': 'age',
        'module': 'child',
        'age_child_months': 15,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (age_child_months-threshold)',
        'symptom': 'age',
        'module': 'child',
        'age_child_months': 24,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (age_child_months-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'age_child_months': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInDays-yes)',
        'symptom': 'age',
        'module': 'child',
        'ageInDays': 1000,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDays-no)',
        'symptom': 'age',
        'module': 'child',
        'ageInDays': 100,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInDays-threshold)',
        'symptom': 'age',
        'module': 'child',
        'ageInDays': 365 * 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDays-upper bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInDays': 12 * 365 - 1,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDays-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInDays': 29,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInDaysNeonate-yes)',
        'symptom': 'age',
        'module': 'child',
        'ageInDaysNeonate': 1000,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDaysNeonate-no)',
        'symptom': 'age',
        'module': 'child',
        'ageInDaysNeonate': 100,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (ageInDaysNeonate-threshold)',
        'symptom': 'age',
        'module': 'child',
        'ageInDaysNeonate': 365 * 2,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDaysNeonate-upper bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInDaysNeonate': 12 * 365 - 1,
        'endorsed': True,
    },
    {
        'sid': 'Child age binary (ageInDaysNeonate-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'ageInDaysNeonate': 29,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (age_child_days-no)',
        'symptom': 'age',
        'module': 'child',
        'age_child_days': 50,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (age_child_days-lower bound)',
        'symptom': 'age',
        'module': 'child',
        'age_child_days': 29,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (isChild)',
        'symptom': 'age',
        'module': 'child',
        'isChild': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (isChild1)',
        'symptom': 'age',
        'module': 'child',
        'isChild1': 1,
        'endorsed': False,
    },
    {
        'sid': 'Child age binary (isChild2)',
        'symptom': 'age',
        'module': 'child',
        'isChild2': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (ageInDays-yes)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDays': 10,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDays-no)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDays': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (ageInDays-threshold)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDays': 3,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDays-upper bound)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDays': 28,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDays-lower bound)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDays': 0,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (ageInDaysNeonate-yes)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDaysNeonate': 10,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDaysNeonate-no)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDaysNeonate': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (ageInDaysNeonate-threshold)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDaysNeonate': 3,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDaysNeonate-upper bound)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDaysNeonate': 28,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (ageInDaysNeonate-lower bound)',
        'symptom': 'age',
        'module': 'neonate',
        'ageInDaysNeonate': 0,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (age_neonate_days-yes)',
        'symptom': 'age',
        'module': 'neonate',
        'age_neonate_days': 10,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (age_neonate_days-no)',
        'symptom': 'age',
        'module': 'neonate',
        'age_neonate_days': 2,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (age_neonate_days-threshold)',
        'symptom': 'age',
        'module': 'neonate',
        'age_neonate_days': 3,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (age_neonate_days-upper bound)',
        'symptom': 'age',
        'module': 'neonate',
        'age_neonate_days': 28,
        'endorsed': True,
    },
    {
        'sid': 'Neonate age binary (age_neonate_days-lower bound)',
        'symptom': 'age',
        'module': 'neonate',
        'age_neonate_days': 0,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (isNeonate)',
        'symptom': 'age',
        'module': 'neonate',
        'isNeonate': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (isNeonate1)',
        'symptom': 'age',
        'module': 'neonate',
        'isNeonate1': 1,
        'endorsed': False,
    },
    {
        'sid': 'Neonate age binary (isNeonate2)',
        'symptom': 'age',
        'module': 'neonate',
        'isNeonate2': 1,
        'endorsed': False,
    },
]
