# coding=utf-8

COUNTRY_DEFAULT = u'Unknown'
COUNTRIES = [
    COUNTRY_DEFAULT,
    u'Afghanistan (AFG)',
    u'Albania (ALB)',
    u'Algeria (DZA)',
    u'Andorra (AND)',
    u'Angola (AGO)',
    u'Antigua and Barbuda (ATG)',
    u'Argentina (ARG)',
    u'Armenia (ARM)',
    u'Australia (AUS)',
    u'Austria (AUT)',
    u'Azerbaijan (AZE)',
    u'Bahamas (BHS)',
    u'Bahrain (BHR)',
    u'Bangladesh (BGD)',
    u'Barbados (BRB)',
    u'Belarus (BLR)',
    u'Belgium (BEL)',
    u'Belize (BLZ)',
    u'Benin (BEN)',
    u'Bhutan (BTN)',
    u'Bolivia, Plurinational State of (BOL)',
    u'Bosnia and Herzegovina (BIH)',
    u'Botswana (BWA)',
    u'Brazil (BRA)',
    u'Brunei Darussalam (BRN)',
    u'Bulgaria (BGR)',
    u'Burkina Faso (BFA)',
    u'Burundi (BDI)',
    u'Cambodia (KHM)',
    u'Cameroon (CMR)',
    u'Canada (CAN)',
    u'Cape Verde (CPV)',
    u'Central African Republic (CAF)',
    u'Chad (TCD)',
    u'Chile (CHL)',
    u'China (CHN)',
    u'Colombia (COL)',
    u'Comoros (COM)',
    u'Congo (COG)',
    u'Congo, the Democratic Republic of the (COD)',
    u'Costa Rica (CRI)',
    u'Côte d\'Ivoire (CIV)',
    u'Croatia (HRV)',
    u'Cuba (CUB)',
    u'Cyprus (CYP)',
    u'Czech Republic (CZE)',
    u'Denmark (DNK)',
    u'Djibouti (DJI)',
    u'Dominica (DMA)',
    u'Dominican Republic (DOM)',
    u'Ecuador (ECU)',
    u'Egypt (EGY)',
    u'El Salvador (SLV)',
    u'Equatorial Guinea (GNQ)',
    u'Eritrea (ERI)',
    u'Estonia (EST)',
    u'Ethiopia (ETH)',
    u'Fiji (FJI)',
    u'Finland (FIN)',
    u'France (FRA)',
    u'Gabon (GAB)',
    u'Gambia (GMB)',
    u'Georgia (GEO)',
    u'Germany (DEU)',
    u'Ghana (GHA)',
    u'Greece (GRC)',
    u'Grenada (GRD)',
    u'Guatemala (GTM)',
    u'Guinea (GIN)',
    u'Guinea-Bissau (GNB)',
    u'Guyana (GUY)',
    u'Haiti (HTI)',
    u'Honduras (HND)',
    u'Hungary (HUN)',
    u'Iceland (ISL)',
    u'India (IND)',
    u'Indonesia (IDN)',
    u'Iran, Islamic Republic of (IRN)',
    u'Iraq (IRQ)',
    u'Ireland (IRL)',
    u'Israel (ISR)',
    u'Italy (ITA)',
    u'Jamaica (JAM)',
    u'Japan (JPN)',
    u'Jordan (JOR)',
    u'Kazakhstan (KAZ)',
    u'Kenya (KEN)',
    u'Kiribati (KIR)',
    u'Korea, Democratic People\'s Republic of (PRK)',
    u'Korea, Republic of (KOR)',
    u'Kuwait (KWT)',
    u'Kyrgyzstan (KGZ)',
    u'Lao People\'s Democratic Republic (LAO)',
    u'Latvia (LVA)',
    u'Lebanon (LBN)',
    u'Lesotho (LSO)',
    u'Liberia (LBR)',
    u'Libyan Arab Jamahiriya (LBY)',
    u'Lithuania (LTU)',
    u'Luxembourg (LUX)',
    u'Macedonia, the former Yugoslav Republic of (MKD)',
    u'Madagascar (MDG)',
    u'Malawi (MWI)',
    u'Malaysia (MYS)',
    u'Maldives (MDV)',
    u'Mali (MLI)',
    u'Malta (MLT)',
    u'Marshall Islands (MHL)',
    u'Mauritania (MRT)',
    u'Mauritius (MUS)',
    u'Mexico (MEX)',
    u'Micronesia, Federated States of (FSM)',
    u'Moldova, Republic of (MDA)',
    u'Mongolia (MNG)',
    u'Montenegro (MNE)',
    u'Morocco (MAR)',
    u'Mozambique (MOZ)',
    u'Myanmar (MMR)',
    u'Namibia (NAM)',
    u'Nepal (NPL)',
    u'Netherlands (NLD)',
    u'New Zealand (NZL)',
    u'Nicaragua (NIC)',
    u'Niger (NER)',
    u'Nigeria (NGA)',
    u'Norway (NOR)',
    u'Oman (OMN)',
    u'Pakistan (PAK)',
    u'Palestinian Territory, Occupied (PSE)',
    u'Panama (PAN)',
    u'Papua New Guinea (PNG)',
    u'Paraguay (PRY)',
    u'Peru (PER)',
    u'Philippines (PHL)',
    u'Poland (POL)',
    u'Portugal (PRT)',
    u'Qatar (QAT)',
    u'Romania (ROU)',
    u'Russian Federation (RUS)',
    u'Rwanda (RWA)',
    u'Saint Lucia (LCA)',
    u'Saint Vincent and the Grenadines (VCT)',
    u'Samoa (WSM)',
    u'Sao Tome and Principe (STP)',
    u'Saudi Arabia (SAU)',
    u'Senegal (SEN)',
    u'Serbia (SRB)',
    u'Seychelles (SYC)',
    u'Sierra Leone (SLE)',
    u'Singapore (SGP)',
    u'Slovakia (SVK)',
    u'Slovenia (SVN)',
    u'Solomon Islands (SLB)',
    u'Somalia (SOM)',
    u'South Africa (ZAF)',
    u'Spain (ESP)',
    u'Sri Lanka (LKA)',
    u'Sudan (SDN)',
    u'Suriname (SUR)',
    u'Swaziland (SWZ)',
    u'Sweden (SWE)',
    u'Switzerland (CHE)',
    u'Syrian Arab Republic (SYR)',
    u'Taiwan, Province of China (TWN)',
    u'Tajikistan (TJK)',
    u'Tanzania, United Republic of (TZA)',
    u'Thailand (THA)',
    u'Timor-Leste (TLS)',
    u'Togo (TGO)',
    u'Tonga (TON)',
    u'Trinidad and Tobago (TTO)',
    u'Tunisia (TUN)',
    u'Turkey (TUR)',
    u'Turkmenistan (TKM)',
    u'Uganda (UGA)',
    u'Ukraine (UKR)',
    u'United Arab Emirates (ARE)',
    u'United Kingdom (GBR)',
    u'United States (USA)',
    u'Uruguay (URY)',
    u'Uzbekistan (UZB)',
    u'Vanuatu (VUT)',
    u'Venezuela, Bolivarian Republic of (VEN)',
    u'Viet Nam (VNM)',
    u'Yemen (YEM)',
    u'Zambia (ZMB)',
    u'Zimbabwe (ZWE)'
]
