# -*- mode: python -*-
a = Analysis(['app.py'],
             pathex=["src/"])
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='SmartVA-Analyze',
          debug=False,
          strip=None,
          upx=False,
          console=True,
          icon='pkg/icon.icns')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               [('res/logo.png', 'src/smartva/res/logo.png', 'DATA')],
               [('res/favicon.ico', 'src/smartva/res/favicon.ico', 'DATA')],
               [('res/about.html', 'src/smartva/res/about.html', 'DATA')],
               [('res/documentation.html', 'src/smartva/res/documentation.html', 'DATA')],
               [('res/documentation.fld/filelist.xml', 'src/smartva/res/documentation.fld/filelist.xml','DATA')],
               [('res/documentation.fld/colorschememapping.xml', 'src/smartva/res/documentation.fld/colorschememapping.xml','DATA')],
               [('res/documentation.fld/themedata.thmx', 'src/smartva/res/documentation.fld/themedata.thmx','DATA')],
               [('res/documentation.fld/item0001.xml', 'src/smartva/res/documentation.fld/item0001.xml','DATA')],
               [('res/documentation.fld/props002.xml', 'src/smartva/res/documentation.fld/props002.xml','DATA')],
               [('res/documentation.fld/image001.png', 'src/smartva/res/documentation.fld/image001.png', 'DATA')],
               [('res/documentation.fld/image002.png', 'src/smartva/res/documentation.fld/image002.png', 'DATA')],
               [('res/documentation.fld/image003.png', 'src/smartva/res/documentation.fld/image003.png', 'DATA')],
               [('res/documentation.fld/image004.png', 'src/smartva/res/documentation.fld/image004.png', 'DATA')],
               [('res/documentation.fld/image005.png', 'src/smartva/res/documentation.fld/image005.png', 'DATA')],
               [('res/documentation.fld/image006.png', 'src/smartva/res/documentation.fld/image006.png', 'DATA')],
               [('res/documentation.fld/image007.png', 'src/smartva/res/documentation.fld/image007.png', 'DATA')],
               [('res/documentation.fld/image008.png', 'src/smartva/res/documentation.fld/image008.png', 'DATA')],
               [('res/documentation.fld/image009.png', 'src/smartva/res/documentation.fld/image009.png', 'DATA')],
               [('res/documentation.fld/image010.png', 'src/smartva/res/documentation.fld/image010.png', 'DATA')],
               [('res/documentation.fld/image011.png', 'src/smartva/res/documentation.fld/image011.png', 'DATA')],
               [('res/documentation.fld/image012.png', 'src/smartva/res/documentation.fld/image012.png', 'DATA')],
               [('res/documentation.fld/image013.png', 'src/smartva/res/documentation.fld/image013.png', 'DATA')],
               [('res/documentation.fld/image014.png', 'src/smartva/res/documentation.fld/image014.png', 'DATA')],
               [('res/documentation.fld/image015.png', 'src/smartva/res/documentation.fld/image015.png', 'DATA')],
               [('res/documentation.fld/image016.png', 'src/smartva/res/documentation.fld/image016.png', 'DATA')],
               [('res/SmartVA Analyze Output Interpretation Sheet.docx', 'src/smartva/res/SmartVA Analyze Output Interpretation Sheet.docx', 'DATA')],
               [('data/tariffs-adult.csv', 'src/smartva/data/tariffs-adult.csv', 'DATA')],
               [('data/tariffs-child.csv', 'src/smartva/data/tariffs-child.csv', 'DATA')],
               [('data/tariffs-neonate.csv', 'src/smartva/data/tariffs-neonate.csv', 'DATA')],
               [('data/validated-adult.csv', 'src/smartva/data/validated-adult.csv', 'DATA')],
               [('data/validated-child.csv', 'src/smartva/data/validated-child.csv', 'DATA')],
               [('data/validated-neonate.csv', 'src/smartva/data/validated-neonate.csv', 'DATA')],
               [('data/chinese.json', 'src/smartva/data/chinese.json', 'DATA')],
               [('data/spanish.json', 'src/smartva/data/spanish.json', 'DATA')],
               [('data/adult_undetermined_weights.csv', 'src/smartva/data/adult_undetermined_weights.csv', 'DATA')],
               [('data/child_undetermined_weights.csv', 'src/smartva/data/child_undetermined_weights.csv', 'DATA')],
               [('data/neonate_undetermined_weights.csv', 'src/smartva/data/neonate_undetermined_weights.csv', 'DATA')],
               strip=None,
               upx=False,
               name='SmartVA-Analyze')
app = BUNDLE(coll,
             name='SmartVA-Analyze.app',
             icon='pkg/icon.icns')
