# -*- mode: python -*-
a = Analysis(['src/vaUI.py'],
             pathex=['/Users/carlhartung/temp/ihme-va'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='SmartVA',
          debug=False,
          strip=None,
          upx=False,
          console=False , icon='pkg/icon.icns')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               [('res/logo.png', '/Users/carlhartung/temp/ihme-va/src/res/logo.png', 'DATA')],
               [('res/about.html', '/Users/carlhartung/temp/ihme-va/src/res/about.html', 'DATA')],
               [('res/documentation.htm', '/Users/carlhartung/temp/ihme-va/src/res/documentation.htm', 'DATA')],
               [('res/documentation_files/header.htm', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/header.htm','DATA')],
               [('res/documentation_files/item0001.xml', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/item0001.xml','DATA')],
               [('res/documentation_files/props0002.xml', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/props0002.xml','DATA')],
               [('res/documentation_files/themedata.xml', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/themedata.xml','DATA')],
               [('res/documentation_files/image001.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image001.png', 'DATA')],
               [('res/documentation_files/image002.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image002.png', 'DATA')],
               [('res/documentation_files/image003.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image003.png', 'DATA')],
               [('res/documentation_files/image004.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image004.png', 'DATA')],
               [('res/documentation_files/image005.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image005.png', 'DATA')],
               [('res/documentation_files/image006.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image006.png', 'DATA')],
               [('res/documentation_files/image007.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image007.png', 'DATA')],
               [('res/documentation_files/image008.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image008.png', 'DATA')],
               [('res/documentation_files/image009.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image009.png', 'DATA')],
               [('res/documentation_files/image010.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image010.png', 'DATA')],
               [('res/documentation_files/image011.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image011.png', 'DATA')],
               [('res/documentation_files/image012.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image012.png', 'DATA')],
               [('res/documentation_files/image013.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image013.png', 'DATA')],
               [('res/documentation_files/image014.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image014.png', 'DATA')],
               [('res/documentation_files/image015.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image015.png', 'DATA')],
               [('res/documentation_files/image016.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image016.png', 'DATA')],
               [('res/documentation_files/image017.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image017.png', 'DATA')],
               [('res/documentation_files/image018.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image018.png', 'DATA')],
               [('res/documentation_files/image019.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image019.png', 'DATA')],
               [('res/documentation_files/image020.png', '/Users/carlhartung/temp/ihme-va/src/res/documentation_files/image020.png', 'DATA')],
               [('tariffs-adult.csv', '/Users/carlhartung/temp/ihme-va/src/tariffs-adult.csv', 'DATA')],
               [('tariffs-child.csv', '/Users/carlhartung/temp/ihme-va/src/tariffs-child.csv', 'DATA')],
               [('tariffs-neonate.csv', '/Users/carlhartung/temp/ihme-va/src/tariffs-neonate.csv', 'DATA')],
               [('validated-adult.csv', '/Users/carlhartung/temp/ihme-va/src/validated-adult.csv', 'DATA')],
               [('validated-child.csv', '/Users/carlhartung/temp/ihme-va/src/validated-child.csv', 'DATA')],
               [('validated-neonate.csv', '/Users/carlhartung/temp/ihme-va/src/validated-neonate.csv', 'DATA')],
               [('adult_undetermined_weights-hce0.csv', '/Users/carlhartung/temp/ihme-va/src/adult_undetermined_weights-hce0.csv', 'DATA')],
               [('adult_undetermined_weights-hce1.csv', '/Users/carlhartung/temp/ihme-va/src/adult_undetermined_weights-hce1.csv', 'DATA')],
               [('child_undetermined_weights-hce0.csv', '/Users/carlhartung/temp/ihme-va/src/child_undetermined_weights-hce0.csv', 'DATA')],
               [('child_undetermined_weights-hce1.csv', '/Users/carlhartung/temp/ihme-va/src/child_undetermined_weights-hce1.csv', 'DATA')],
               [('neonate_undetermined_weights-hce0.csv', '/Users/carlhartung/temp/ihme-va/src/neonate_undetermined_weights-hce0.csv', 'DATA')],
               [('neonate_undetermined_weights-hce1.csv', '/Users/carlhartung/temp/ihme-va/src/neonate_undetermined_weights-hce1.csv', 'DATA')],
               strip=None,
               upx=False,
               name='SmartVA')
app = BUNDLE(coll,
             name='SmartVA.app',
             icon='pkg/icon.icns')
